// <auto-generated />
using DesafioTecnico.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioTecnico.API.Migrations
{
    [DbContext(typeof(EstoqueDbContext))]
    [Migration("20261009162705_InserirProdutosIniciais")]
    partial class InserirProdutosIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesafioTecnico.API.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstoqueAtual")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovimentacoesEstoque");
                });

            modelBuilder.Entity("Produto", b =>
                {
                    b.Property<int>("CodigoProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoProduto"));

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.HasKey("CodigoProduto");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            CodigoProduto = 101,
                            DescricaoProduto = "Caneta Azul",
                            Estoque = 150
                        },
                        new
                        {
                            CodigoProduto = 102,
                            DescricaoProduto = "Caderno Universitário",
                            Estoque = 75
                        },
                        new
                        {
                            CodigoProduto = 103,
                            DescricaoProduto = "Borracha Branca",
                            Estoque = 200
                        },
                        new
                        {
                            CodigoProduto = 104,
                            DescricaoProduto = "Lápis Preto HB",
                            Estoque = 320
                        },
                        new
                        {
                            CodigoProduto = 105,
                            DescricaoProduto = "Marcador de Texto Amarelo",
                            Estoque = 90
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
